# Generated by Django 5.2.7 on 2025-11-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_column_color_task_archived_comment_workspacemember"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="workspacemember",
            constraint=models.UniqueConstraint(
                fields=("workspace", "user"), name="uniq_workspace_user"
            ),
        ),
    ]
