# Generated by Django 5.2.7 on 2025-11-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0003_alter_workspacemember_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="boards.column",
            ),
        ),
    ]
